// set up events for our socket
module.exports = {
  PUBLIC_CHAT: 'PUBLIC_CHAT',
  USER_CONNECTED: 'USER_CONNECTED',
  MESSAGE_RECIEVED: 'MESSAGE_RECIEVED',
  MESSAGE_SENT: 'MESSAGE_SENT',
  USER_DISCONNECTED: 'USER_DISCONNECTED',
  VERIFY_USER: 'VERIFY_USER',
  LOGOUT: 'LOGOUT',
  PRIVATE_MESSAGE: 'PRIVATE_MESSAGE',
  SEND_TO_USER: 'SEND_TO_USER',
  GET_CONNECTED_USERS: 'GET_CONNECTED_USERS',
};
